import type { NextPage } from 'next'
import { Suspense } from 'react'
import Head from 'next/head'
import { Container, Loader, Skeleton } from '@mantine/core'

import Main from 'components/Main'
const Banner = dynamic(() => import('components/Home/Banner'), {
  suspense:true
})
import SubBanner from 'components/Home/SubBanner'
import GridBanner from 'components/Home/GridBanner'
import dynamic from 'next/dynamic'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main>
        <Suspense fallback={<Loader/>}>
          <Container size='xl'>
            <Banner />
          </Container>
        </Suspense>
        <SubBanner />
        <Container size='xl'>
          <GridBanner />
        </Container>
      </Main>
    </>
  )
}

const child = <Skeleton height={140} radius='md' animate={false} />

export default Home
